fix "make swig"
../sql/view.c:115:7: error: conflicting types for 'AK_get_relation_expression'
  115 | char *AK_get_relation_expression(char *name)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from implementation.h:12,
                 from kalashnikovDB_wrap.c:2761:
../opti/query_optimization.c:172:18: note: previous implicit declaration of 'AK_get_relation_expression' was here
  172 |   char* record = AK_get_relation_expression(list_elem->data);

Error was caused by view.c being included after query_optimization.c, AK_get_relation_expression was not declared before being referenced